In [1]:
import numpy as np
np.set_printoptions(precision=3,suppress=True)

x=np.array([
    [1.0, 2.0, 30.0],
    [2.0, 4.0, 32.0],
    [3.0, 6.0, 28.0],
    [4.0, 8.0, 34.0],

])

print("Input data: \n",x)

Input data: 
 [[ 1.  2. 30.]
 [ 2.  4. 32.]
 [ 3.  6. 28.]
 [ 4.  8. 34.]]


In [3]:
eps = 1e-5

mean = x.mean(axis=0)
var = x.var(axis=0)

print("mean per feature:", mean)
print("var per feature:", var)

x_hat = (x-mean)/ np.sqrt(var + eps)
print("\nNormalized x (x_hat):\n",x_hat)
print("\nnew mean per feature (should be ~0):", x_hat.mean(axis=0))
print("new var per feature (should be ~1):", x_hat.var(axis=0))

mean per feature: [ 2.5  5.  31. ]
var per feature: [1.25 5.   5.  ]

Normalized x (x_hat):
 [[-1.342 -1.342 -0.447]
 [-0.447 -0.447  0.447]
 [ 0.447  0.447 -1.342]
 [ 1.342  1.342  1.342]]

new mean per feature (should be ~0): [0. 0. 0.]
new var per feature (should be ~1): [1. 1. 1.]


In [5]:
gamma=np.ones(3)
beta=np.zeros(3)

out=gamma* x_hat + beta
print("Output after gamma/ betta:\n", out)

Output after gamma/ betta:
 [[-1.342 -1.342 -0.447]
 [-0.447 -0.447  0.447]
 [ 0.447  0.447 -1.342]
 [ 1.342  1.342  1.342]]


In [7]:
mean_ln = x.mean(axis=1, keepdims=True)
var_ln = x.var(axis=1, keepdims=True)

x_hat_ln = (x-mean_ln) / np.sqrt (var_ln + eps)
print("LayerNorm normalized x:\n", x_hat_ln)
print("\nrow means(should be ~0):", x_hat_ln.mean(axis=1))
print("row vars (should be ~1):", x_hat_ln.var(axis=1))

LayerNorm normalized x:
 [[-0.744 -0.67   1.414]
 [-0.779 -0.633  1.412]
 [-0.837 -0.568  1.406]
 [-0.852 -0.551  1.404]]

row means(should be ~0): [ 0.  0. -0. -0.]
row vars (should be ~1): [1. 1. 1. 1.]
